/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class il_ac_technion_eyalzo_NFQueue */

#ifndef _Included_il_ac_technion_eyalzo_NFQueue
#define _Included_il_ac_technion_eyalzo_NFQueue
#ifdef __cplusplus
extern "C" {
#endif
#undef il_ac_technion_eyalzo_NFQueue_NFQ_JAVA_VERSION
#define il_ac_technion_eyalzo_NFQueue_NFQ_JAVA_VERSION 4L
/* Inaccessible static: c_libLoaded */
/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    newNativeQueue
 * Signature: (SI)J
 */
JNIEXPORT jlong JNICALL Java_il_ac_technion_eyalzo_NFQueue_newNativeQueue
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    deleteNativeQueue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_il_ac_technion_eyalzo_NFQueue_deleteNativeQueue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    nativeLoop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_il_ac_technion_eyalzo_NFQueue_nativeLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    nativeBreakLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_il_ac_technion_eyalzo_NFQueue_nativeBreakLoop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    setCopyMode
 * Signature: (JBI)V
 */
JNIEXPORT void JNICALL Java_il_ac_technion_eyalzo_NFQueue_setCopyMode
  (JNIEnv *, jobject, jlong, jbyte, jint);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    setRecvBufferSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_il_ac_technion_eyalzo_NFQueue_setRecvBufferSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    getNativeVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_il_ac_technion_eyalzo_NFQueue_getNativeVersion
  (JNIEnv *, jclass);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    getPacketPayload
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_il_ac_technion_eyalzo_NFQueue_getPacketPayload
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     il_ac_technion_eyalzo_NFQueue
 * Method:    getLastErrorMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_il_ac_technion_eyalzo_NFQueue_getLastErrorMsg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
